// lib/testMovies.ts

export const testMovies = [
  {
    id: 2001,
    title: "The Conjuring",
    category: "Supernatural & Mystery",
    genres: "Horror, Supernatural, Thriller",
    releaseDate: "2013",
    poster: "/conjuring.jpg",
    rating: 9,
  },
  {
    id: 2002,
    title: "Insidious",
    category: "Supernatural & Mystery",
    genres: "Horror, Supernatural, Thriller",
    releaseDate: "2010",
    poster: "/insidious.jpg",
    rating: 8,
  },
  {
    id: 2003,
    title: "The Autopsy of Jane Doe",
    category: "Supernatural & Mystery",
    genres: "Horror, Mystery, Supernatural",
    releaseDate: "2016",
    poster: "/autopsy-of-jane-doe.jpg",
    rating: 8,
  },
  {
    id: 3001,
    title: "The Texas Chainsaw Massacre",
    category: "Slashers & Thrillers",
    genres: "Horror, Slasher, Thriller",
    releaseDate: "1974",
    poster: "/texas-chainsaw-massacre.jpg",
    rating: 9,
  },
  {
    id: 3002,
    title: "Halloween",
    category: "Slashers & Thrillers",
    genres: "Horror, Slasher, Thriller",
    releaseDate: "1978",
    poster: "/halloween.jpg",
    rating: 9,
  },
  {
    id: 3003,
    title: "A Nightmare on Elm Street",
    category: "Slashers & Thrillers",
    genres: "Horror, Slasher, Thriller",
    releaseDate: "1984",
    poster: "/nightmare-on-elm-street.jpg",
    rating: 9,
  },
];
